apiVersion: v1
kind: Deployment
metadata:
  namespace: breadbook
  name: frontend-deployment-COLOR
spec:
  replicas: 2
  selector:
    matchLabels:
      type: frontend
      deployment: front-COLOR
  template:
    metadata:
      labels:
        type: frontend
        deployment: front-COLOR
    spec:
      # initContainers:
      #   - name : init-html
      #     image: busybox
      #     command: ["sh", "-c", "echo test > /usr/share/nginx/html/test.html"]
      #     volumeMounts:
      #       - name: nginx-vol
      #         mountPath: /usr/share/nginx/html
      containers:
        - name: front
          image: iuch/breadbook-front:14
          volumeMounts:
            - name: image-upload
              mountPath: /mnt
          ports:
            - containerPort: 80
      volumes:
        - name: image-upload
          persistentVolumeClaim:
            claimName: image-pvc
